# Uncomment this line to define a global platform for your project
platform :ios, "6.0"

# ignore all warnings from all pods
inhibit_all_warnings!

# ignore warnings from a specific pod
# pod 'Facebook-iOS-SDK', :inhibit_warnings => true

pod 'libextobjc'

# Network & Data
pod 'AFNetworking', '~> 1.3'


# UI Controls

pod 'MMProgressHUD', :git => 'https://github.com/lanvige/MMProgressHUD'

# target "Compass" do
# end